DROP PROCEDURE IF EXISTS ELIMINAR_STAFF_ACTIVO;
DELIMITER $$

CREATE PROCEDURE ELIMINAR_STAFF_ACTIVO(
    IN p_id_staff INT
)
BEGIN
    UPDATE Staff
    SET estado = 'INACTIVO'
    WHERE id_staff = p_id_staff;
END$$

DELIMITER ;