DROP PROCEDURE IF EXISTS ELIMINAR_POSTULANTE;
DELIMITER $$
CREATE PROCEDURE ELIMINAR_POSTULANTE(
	IN id INT
)
BEGIN
	DELETE FROM Postulante WHERE id_postulante = id;
	CALL ELIMINAR_MIEMBROPUCP(id);
END$$
DELIMITER ;