//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDPTalentoWA.StaffWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.core.gdptalento.pucp.edu.pe/", ConfigurationName="StaffWS.StaffWS")]
    public interface StaffWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.core.gdptalento.pucp.edu.pe/StaffWS/eliminarStaffRequest", ReplyAction="http://ws.core.gdptalento.pucp.edu.pe/StaffWS/eliminarStaffResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GDPTalentoWA.StaffWS.eliminarStaffResponse eliminarStaff(GDPTalentoWA.StaffWS.eliminarStaffRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.core.gdptalento.pucp.edu.pe/StaffWS/eliminarStaffRequest", ReplyAction="http://ws.core.gdptalento.pucp.edu.pe/StaffWS/eliminarStaffResponse")]
        System.Threading.Tasks.Task<GDPTalentoWA.StaffWS.eliminarStaffResponse> eliminarStaffAsync(GDPTalentoWA.StaffWS.eliminarStaffRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.core.gdptalento.pucp.edu.pe/StaffWS/insertarStaffRequest", ReplyAction="http://ws.core.gdptalento.pucp.edu.pe/StaffWS/insertarStaffResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(miembroPUCP))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GDPTalentoWA.StaffWS.insertarStaffResponse insertarStaff(GDPTalentoWA.StaffWS.insertarStaffRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.core.gdptalento.pucp.edu.pe/StaffWS/insertarStaffRequest", ReplyAction="http://ws.core.gdptalento.pucp.edu.pe/StaffWS/insertarStaffResponse")]
        System.Threading.Tasks.Task<GDPTalentoWA.StaffWS.insertarStaffResponse> insertarStaffAsync(GDPTalentoWA.StaffWS.insertarStaffRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.core.gdptalento.pucp.edu.pe/StaffWS/modificarStaffRequest", ReplyAction="http://ws.core.gdptalento.pucp.edu.pe/StaffWS/modificarStaffResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(miembroPUCP))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GDPTalentoWA.StaffWS.modificarStaffResponse modificarStaff(GDPTalentoWA.StaffWS.modificarStaffRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.core.gdptalento.pucp.edu.pe/StaffWS/modificarStaffRequest", ReplyAction="http://ws.core.gdptalento.pucp.edu.pe/StaffWS/modificarStaffResponse")]
        System.Threading.Tasks.Task<GDPTalentoWA.StaffWS.modificarStaffResponse> modificarStaffAsync(GDPTalentoWA.StaffWS.modificarStaffRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.core.gdptalento.pucp.edu.pe/StaffWS/listarStaffRequest", ReplyAction="http://ws.core.gdptalento.pucp.edu.pe/StaffWS/listarStaffResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(miembroPUCP))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GDPTalentoWA.StaffWS.listarStaffResponse listarStaff(GDPTalentoWA.StaffWS.listarStaffRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.core.gdptalento.pucp.edu.pe/StaffWS/listarStaffRequest", ReplyAction="http://ws.core.gdptalento.pucp.edu.pe/StaffWS/listarStaffResponse")]
        System.Threading.Tasks.Task<GDPTalentoWA.StaffWS.listarStaffResponse> listarStaffAsync(GDPTalentoWA.StaffWS.listarStaffRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarStaff", WrapperNamespace="http://ws.core.gdptalento.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarStaffRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.core.gdptalento.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idstaff;
        
        public eliminarStaffRequest() {
        }
        
        public eliminarStaffRequest(int idstaff) {
            this.idstaff = idstaff;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarStaffResponse", WrapperNamespace="http://ws.core.gdptalento.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarStaffResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.core.gdptalento.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarStaffResponse() {
        }
        
        public eliminarStaffResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(usuario))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.core.gdptalento.pucp.edu.pe/")]
    public partial class staff : miembroPUCP {
        
        private area areaField;
        
        private bool areaFieldSpecified;
        
        private double desempenioField;
        
        private estadoMiembro estadoField;
        
        private bool estadoFieldSpecified;
        
        private evaluacionDesempeño[] evaluacionesField;
        
        private localDate fechaIngresoField;
        
        private localDate fechaSalidaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public area area {
            get {
                return this.areaField;
            }
            set {
                this.areaField = value;
                this.RaisePropertyChanged("area");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool areaSpecified {
            get {
                return this.areaFieldSpecified;
            }
            set {
                this.areaFieldSpecified = value;
                this.RaisePropertyChanged("areaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double desempenio {
            get {
                return this.desempenioField;
            }
            set {
                this.desempenioField = value;
                this.RaisePropertyChanged("desempenio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public estadoMiembro estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("evaluaciones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public evaluacionDesempeño[] evaluaciones {
            get {
                return this.evaluacionesField;
            }
            set {
                this.evaluacionesField = value;
                this.RaisePropertyChanged("evaluaciones");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public localDate fechaIngreso {
            get {
                return this.fechaIngresoField;
            }
            set {
                this.fechaIngresoField = value;
                this.RaisePropertyChanged("fechaIngreso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public localDate fechaSalida {
            get {
                return this.fechaSalidaField;
            }
            set {
                this.fechaSalidaField = value;
                this.RaisePropertyChanged("fechaSalida");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.core.gdptalento.pucp.edu.pe/")]
    public enum area {
        
        /// <remarks/>
        RECURSOS_HUMANOS,
        
        /// <remarks/>
        PRESIDENCIA,
        
        /// <remarks/>
        MARKETING,
        
        /// <remarks/>
        GDP_ACADEMY,
        
        /// <remarks/>
        EVENTOS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.core.gdptalento.pucp.edu.pe/")]
    public enum estadoMiembro {
        
        /// <remarks/>
        ACTIVO,
        
        /// <remarks/>
        INACTIVO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.core.gdptalento.pucp.edu.pe/")]
    public partial class evaluacionDesempeño : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string comentariosField;
        
        private usuario evaluadorField;
        
        private localDate fechaField;
        
        private int idField;
        
        private staff miembroEvaluadoField;
        
        private int puntajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string comentarios {
            get {
                return this.comentariosField;
            }
            set {
                this.comentariosField = value;
                this.RaisePropertyChanged("comentarios");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public usuario evaluador {
            get {
                return this.evaluadorField;
            }
            set {
                this.evaluadorField = value;
                this.RaisePropertyChanged("evaluador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public localDate fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public staff miembroEvaluado {
            get {
                return this.miembroEvaluadoField;
            }
            set {
                this.miembroEvaluadoField = value;
                this.RaisePropertyChanged("miembroEvaluado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int puntaje {
            get {
                return this.puntajeField;
            }
            set {
                this.puntajeField = value;
                this.RaisePropertyChanged("puntaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.core.gdptalento.pucp.edu.pe/")]
    public partial class usuario : staff {
        
        private string hashContrasenaField;
        
        private rol rolField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string hashContrasena {
            get {
                return this.hashContrasenaField;
            }
            set {
                this.hashContrasenaField = value;
                this.RaisePropertyChanged("hashContrasena");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public rol rol {
            get {
                return this.rolField;
            }
            set {
                this.rolField = value;
                this.RaisePropertyChanged("rol");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.core.gdptalento.pucp.edu.pe/")]
    public partial class rol : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private nombreRol nombreField;
        
        private bool nombreFieldSpecified;
        
        private System.Nullable<permiso>[] permisosField;
        
        private usuario[] usuariosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public nombreRol nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nombreSpecified {
            get {
                return this.nombreFieldSpecified;
            }
            set {
                this.nombreFieldSpecified = value;
                this.RaisePropertyChanged("nombreSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("permisos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public System.Nullable<permiso>[] permisos {
            get {
                return this.permisosField;
            }
            set {
                this.permisosField = value;
                this.RaisePropertyChanged("permisos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("usuarios", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public usuario[] usuarios {
            get {
                return this.usuariosField;
            }
            set {
                this.usuariosField = value;
                this.RaisePropertyChanged("usuarios");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.core.gdptalento.pucp.edu.pe/")]
    public enum nombreRol {
        
        /// <remarks/>
        ADMIN,
        
        /// <remarks/>
        RECLUTADOR,
        
        /// <remarks/>
        COORDINADOR,
        
        /// <remarks/>
        DIRECTOR_RRHH,
        
        /// <remarks/>
        MIEMBRO_RRHH,
        
        /// <remarks/>
        PRESIDENTE,
        
        /// <remarks/>
        DIRECTOR_MARKETING,
        
        /// <remarks/>
        DIRECTOR_EVENTOS,
        
        /// <remarks/>
        DIRECTOR_GDP_ACADEMY,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.core.gdptalento.pucp.edu.pe/")]
    public enum permiso {
        
        /// <remarks/>
        CREAR_MIEMBRO,
        
        /// <remarks/>
        BORRAR_MIEMBRO,
        
        /// <remarks/>
        CREAR_TAREA,
        
        /// <remarks/>
        CREAR_ENTREVISTA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.core.gdptalento.pucp.edu.pe/")]
    public partial class localDate : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(staff))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(usuario))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.core.gdptalento.pucp.edu.pe/")]
    public partial class miembroPUCP : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoPUCPField;
        
        private string correoField;
        
        private string especialidadField;
        
        private string facultadField;
        
        private int idField;
        
        private string nombreField;
        
        private estadoPUCP statusField;
        
        private bool statusFieldSpecified;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoPUCP {
            get {
                return this.codigoPUCPField;
            }
            set {
                this.codigoPUCPField = value;
                this.RaisePropertyChanged("codigoPUCP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string especialidad {
            get {
                return this.especialidadField;
            }
            set {
                this.especialidadField = value;
                this.RaisePropertyChanged("especialidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string facultad {
            get {
                return this.facultadField;
            }
            set {
                this.facultadField = value;
                this.RaisePropertyChanged("facultad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public estadoPUCP status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
                this.RaisePropertyChanged("statusSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.core.gdptalento.pucp.edu.pe/")]
    public enum estadoPUCP {
        
        /// <remarks/>
        MATRICULADO,
        
        /// <remarks/>
        NO_MATRICULADO,
        
        /// <remarks/>
        EGRESADO,
        
        /// <remarks/>
        EXTERNO,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarStaff", WrapperNamespace="http://ws.core.gdptalento.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarStaffRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.core.gdptalento.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GDPTalentoWA.StaffWS.staff staff;
        
        public insertarStaffRequest() {
        }
        
        public insertarStaffRequest(GDPTalentoWA.StaffWS.staff staff) {
            this.staff = staff;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarStaffResponse", WrapperNamespace="http://ws.core.gdptalento.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarStaffResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.core.gdptalento.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarStaffResponse() {
        }
        
        public insertarStaffResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarStaff", WrapperNamespace="http://ws.core.gdptalento.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarStaffRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.core.gdptalento.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GDPTalentoWA.StaffWS.staff staff;
        
        public modificarStaffRequest() {
        }
        
        public modificarStaffRequest(GDPTalentoWA.StaffWS.staff staff) {
            this.staff = staff;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarStaffResponse", WrapperNamespace="http://ws.core.gdptalento.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarStaffResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.core.gdptalento.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarStaffResponse() {
        }
        
        public modificarStaffResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarStaff", WrapperNamespace="http://ws.core.gdptalento.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarStaffRequest {
        
        public listarStaffRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarStaffResponse", WrapperNamespace="http://ws.core.gdptalento.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarStaffResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.core.gdptalento.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GDPTalentoWA.StaffWS.staff[] @return;
        
        public listarStaffResponse() {
        }
        
        public listarStaffResponse(GDPTalentoWA.StaffWS.staff[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StaffWSChannel : GDPTalentoWA.StaffWS.StaffWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StaffWSClient : System.ServiceModel.ClientBase<GDPTalentoWA.StaffWS.StaffWS>, GDPTalentoWA.StaffWS.StaffWS {
        
        public StaffWSClient() {
        }
        
        public StaffWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StaffWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StaffWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StaffWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GDPTalentoWA.StaffWS.eliminarStaffResponse GDPTalentoWA.StaffWS.StaffWS.eliminarStaff(GDPTalentoWA.StaffWS.eliminarStaffRequest request) {
            return base.Channel.eliminarStaff(request);
        }
        
        public int eliminarStaff(int idstaff) {
            GDPTalentoWA.StaffWS.eliminarStaffRequest inValue = new GDPTalentoWA.StaffWS.eliminarStaffRequest();
            inValue.idstaff = idstaff;
            GDPTalentoWA.StaffWS.eliminarStaffResponse retVal = ((GDPTalentoWA.StaffWS.StaffWS)(this)).eliminarStaff(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GDPTalentoWA.StaffWS.eliminarStaffResponse> GDPTalentoWA.StaffWS.StaffWS.eliminarStaffAsync(GDPTalentoWA.StaffWS.eliminarStaffRequest request) {
            return base.Channel.eliminarStaffAsync(request);
        }
        
        public System.Threading.Tasks.Task<GDPTalentoWA.StaffWS.eliminarStaffResponse> eliminarStaffAsync(int idstaff) {
            GDPTalentoWA.StaffWS.eliminarStaffRequest inValue = new GDPTalentoWA.StaffWS.eliminarStaffRequest();
            inValue.idstaff = idstaff;
            return ((GDPTalentoWA.StaffWS.StaffWS)(this)).eliminarStaffAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GDPTalentoWA.StaffWS.insertarStaffResponse GDPTalentoWA.StaffWS.StaffWS.insertarStaff(GDPTalentoWA.StaffWS.insertarStaffRequest request) {
            return base.Channel.insertarStaff(request);
        }
        
        public int insertarStaff(GDPTalentoWA.StaffWS.staff staff) {
            GDPTalentoWA.StaffWS.insertarStaffRequest inValue = new GDPTalentoWA.StaffWS.insertarStaffRequest();
            inValue.staff = staff;
            GDPTalentoWA.StaffWS.insertarStaffResponse retVal = ((GDPTalentoWA.StaffWS.StaffWS)(this)).insertarStaff(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GDPTalentoWA.StaffWS.insertarStaffResponse> GDPTalentoWA.StaffWS.StaffWS.insertarStaffAsync(GDPTalentoWA.StaffWS.insertarStaffRequest request) {
            return base.Channel.insertarStaffAsync(request);
        }
        
        public System.Threading.Tasks.Task<GDPTalentoWA.StaffWS.insertarStaffResponse> insertarStaffAsync(GDPTalentoWA.StaffWS.staff staff) {
            GDPTalentoWA.StaffWS.insertarStaffRequest inValue = new GDPTalentoWA.StaffWS.insertarStaffRequest();
            inValue.staff = staff;
            return ((GDPTalentoWA.StaffWS.StaffWS)(this)).insertarStaffAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GDPTalentoWA.StaffWS.modificarStaffResponse GDPTalentoWA.StaffWS.StaffWS.modificarStaff(GDPTalentoWA.StaffWS.modificarStaffRequest request) {
            return base.Channel.modificarStaff(request);
        }
        
        public int modificarStaff(GDPTalentoWA.StaffWS.staff staff) {
            GDPTalentoWA.StaffWS.modificarStaffRequest inValue = new GDPTalentoWA.StaffWS.modificarStaffRequest();
            inValue.staff = staff;
            GDPTalentoWA.StaffWS.modificarStaffResponse retVal = ((GDPTalentoWA.StaffWS.StaffWS)(this)).modificarStaff(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GDPTalentoWA.StaffWS.modificarStaffResponse> GDPTalentoWA.StaffWS.StaffWS.modificarStaffAsync(GDPTalentoWA.StaffWS.modificarStaffRequest request) {
            return base.Channel.modificarStaffAsync(request);
        }
        
        public System.Threading.Tasks.Task<GDPTalentoWA.StaffWS.modificarStaffResponse> modificarStaffAsync(GDPTalentoWA.StaffWS.staff staff) {
            GDPTalentoWA.StaffWS.modificarStaffRequest inValue = new GDPTalentoWA.StaffWS.modificarStaffRequest();
            inValue.staff = staff;
            return ((GDPTalentoWA.StaffWS.StaffWS)(this)).modificarStaffAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GDPTalentoWA.StaffWS.listarStaffResponse GDPTalentoWA.StaffWS.StaffWS.listarStaff(GDPTalentoWA.StaffWS.listarStaffRequest request) {
            return base.Channel.listarStaff(request);
        }
        
        public GDPTalentoWA.StaffWS.staff[] listarStaff() {
            GDPTalentoWA.StaffWS.listarStaffRequest inValue = new GDPTalentoWA.StaffWS.listarStaffRequest();
            GDPTalentoWA.StaffWS.listarStaffResponse retVal = ((GDPTalentoWA.StaffWS.StaffWS)(this)).listarStaff(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GDPTalentoWA.StaffWS.listarStaffResponse> GDPTalentoWA.StaffWS.StaffWS.listarStaffAsync(GDPTalentoWA.StaffWS.listarStaffRequest request) {
            return base.Channel.listarStaffAsync(request);
        }
        
        public System.Threading.Tasks.Task<GDPTalentoWA.StaffWS.listarStaffResponse> listarStaffAsync() {
            GDPTalentoWA.StaffWS.listarStaffRequest inValue = new GDPTalentoWA.StaffWS.listarStaffRequest();
            return ((GDPTalentoWA.StaffWS.StaffWS)(this)).listarStaffAsync(inValue);
        }
    }
}
