DROP PROCEDURE IF EXISTS OBTENER_PROXIMA_ENTREVISTA;

DELIMITER $$
CREATE PROCEDURE OBTENER_PROXIMA_ENTREVISTA()
BEGIN
  SELECT 
    MIN(fecha) AS proxima
  FROM Entrevista
  WHERE estado = 'PROGRAMADA'
    AND fecha >= CURDATE();
END$$
DELIMITER ;
