//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDPTalentoWA.MiembroPUCPWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.core.gdptalento.pucp.edu.pe/", ConfigurationName="MiembroPUCPWS.MiembroPUCPWS")]
    public interface MiembroPUCPWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.core.gdptalento.pucp.edu.pe/MiembroPUCPWS/modificarMiembroPUCPRequest", ReplyAction="http://ws.core.gdptalento.pucp.edu.pe/MiembroPUCPWS/modificarMiembroPUCPResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GDPTalentoWA.MiembroPUCPWS.modificarMiembroPUCPResponse modificarMiembroPUCP(GDPTalentoWA.MiembroPUCPWS.modificarMiembroPUCPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.core.gdptalento.pucp.edu.pe/MiembroPUCPWS/modificarMiembroPUCPRequest", ReplyAction="http://ws.core.gdptalento.pucp.edu.pe/MiembroPUCPWS/modificarMiembroPUCPResponse")]
        System.Threading.Tasks.Task<GDPTalentoWA.MiembroPUCPWS.modificarMiembroPUCPResponse> modificarMiembroPUCPAsync(GDPTalentoWA.MiembroPUCPWS.modificarMiembroPUCPRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.core.gdptalento.pucp.edu.pe/MiembroPUCPWS/insertarMiembroPUCPRequest", ReplyAction="http://ws.core.gdptalento.pucp.edu.pe/MiembroPUCPWS/insertarMiembroPUCPResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GDPTalentoWA.MiembroPUCPWS.insertarMiembroPUCPResponse insertarMiembroPUCP(GDPTalentoWA.MiembroPUCPWS.insertarMiembroPUCPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.core.gdptalento.pucp.edu.pe/MiembroPUCPWS/insertarMiembroPUCPRequest", ReplyAction="http://ws.core.gdptalento.pucp.edu.pe/MiembroPUCPWS/insertarMiembroPUCPResponse")]
        System.Threading.Tasks.Task<GDPTalentoWA.MiembroPUCPWS.insertarMiembroPUCPResponse> insertarMiembroPUCPAsync(GDPTalentoWA.MiembroPUCPWS.insertarMiembroPUCPRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.core.gdptalento.pucp.edu.pe/MiembroPUCPWS/eliminarMiembroPUCPRequest", ReplyAction="http://ws.core.gdptalento.pucp.edu.pe/MiembroPUCPWS/eliminarMiembroPUCPResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GDPTalentoWA.MiembroPUCPWS.eliminarMiembroPUCPResponse eliminarMiembroPUCP(GDPTalentoWA.MiembroPUCPWS.eliminarMiembroPUCPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.core.gdptalento.pucp.edu.pe/MiembroPUCPWS/eliminarMiembroPUCPRequest", ReplyAction="http://ws.core.gdptalento.pucp.edu.pe/MiembroPUCPWS/eliminarMiembroPUCPResponse")]
        System.Threading.Tasks.Task<GDPTalentoWA.MiembroPUCPWS.eliminarMiembroPUCPResponse> eliminarMiembroPUCPAsync(GDPTalentoWA.MiembroPUCPWS.eliminarMiembroPUCPRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.core.gdptalento.pucp.edu.pe/MiembroPUCPWS/listarMiembroPUCPRequest", ReplyAction="http://ws.core.gdptalento.pucp.edu.pe/MiembroPUCPWS/listarMiembroPUCPResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GDPTalentoWA.MiembroPUCPWS.listarMiembroPUCPResponse listarMiembroPUCP(GDPTalentoWA.MiembroPUCPWS.listarMiembroPUCPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.core.gdptalento.pucp.edu.pe/MiembroPUCPWS/listarMiembroPUCPRequest", ReplyAction="http://ws.core.gdptalento.pucp.edu.pe/MiembroPUCPWS/listarMiembroPUCPResponse")]
        System.Threading.Tasks.Task<GDPTalentoWA.MiembroPUCPWS.listarMiembroPUCPResponse> listarMiembroPUCPAsync(GDPTalentoWA.MiembroPUCPWS.listarMiembroPUCPRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.core.gdptalento.pucp.edu.pe/")]
    public partial class miembroPUCP : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoPUCPField;
        
        private string correoField;
        
        private string especialidadField;
        
        private string facultadField;
        
        private int idField;
        
        private string nombreField;
        
        private estadoPUCP statusField;
        
        private bool statusFieldSpecified;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoPUCP {
            get {
                return this.codigoPUCPField;
            }
            set {
                this.codigoPUCPField = value;
                this.RaisePropertyChanged("codigoPUCP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string especialidad {
            get {
                return this.especialidadField;
            }
            set {
                this.especialidadField = value;
                this.RaisePropertyChanged("especialidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string facultad {
            get {
                return this.facultadField;
            }
            set {
                this.facultadField = value;
                this.RaisePropertyChanged("facultad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public estadoPUCP status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
                this.RaisePropertyChanged("statusSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.core.gdptalento.pucp.edu.pe/")]
    public enum estadoPUCP {
        
        /// <remarks/>
        MATRICULADO,
        
        /// <remarks/>
        NO_MATRICULADO,
        
        /// <remarks/>
        EGRESADO,
        
        /// <remarks/>
        EXTERNO,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarMiembroPUCP", WrapperNamespace="http://ws.core.gdptalento.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarMiembroPUCPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.core.gdptalento.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GDPTalentoWA.MiembroPUCPWS.miembroPUCP miembroPUCP;
        
        public modificarMiembroPUCPRequest() {
        }
        
        public modificarMiembroPUCPRequest(GDPTalentoWA.MiembroPUCPWS.miembroPUCP miembroPUCP) {
            this.miembroPUCP = miembroPUCP;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarMiembroPUCPResponse", WrapperNamespace="http://ws.core.gdptalento.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarMiembroPUCPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.core.gdptalento.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarMiembroPUCPResponse() {
        }
        
        public modificarMiembroPUCPResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarMiembroPUCP", WrapperNamespace="http://ws.core.gdptalento.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarMiembroPUCPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.core.gdptalento.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GDPTalentoWA.MiembroPUCPWS.miembroPUCP miembroPUCP;
        
        public insertarMiembroPUCPRequest() {
        }
        
        public insertarMiembroPUCPRequest(GDPTalentoWA.MiembroPUCPWS.miembroPUCP miembroPUCP) {
            this.miembroPUCP = miembroPUCP;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarMiembroPUCPResponse", WrapperNamespace="http://ws.core.gdptalento.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarMiembroPUCPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.core.gdptalento.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarMiembroPUCPResponse() {
        }
        
        public insertarMiembroPUCPResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarMiembroPUCP", WrapperNamespace="http://ws.core.gdptalento.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarMiembroPUCPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.core.gdptalento.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idmiembroPUCP;
        
        public eliminarMiembroPUCPRequest() {
        }
        
        public eliminarMiembroPUCPRequest(int idmiembroPUCP) {
            this.idmiembroPUCP = idmiembroPUCP;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarMiembroPUCPResponse", WrapperNamespace="http://ws.core.gdptalento.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarMiembroPUCPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.core.gdptalento.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarMiembroPUCPResponse() {
        }
        
        public eliminarMiembroPUCPResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarMiembroPUCP", WrapperNamespace="http://ws.core.gdptalento.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarMiembroPUCPRequest {
        
        public listarMiembroPUCPRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarMiembroPUCPResponse", WrapperNamespace="http://ws.core.gdptalento.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarMiembroPUCPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.core.gdptalento.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GDPTalentoWA.MiembroPUCPWS.miembroPUCP[] @return;
        
        public listarMiembroPUCPResponse() {
        }
        
        public listarMiembroPUCPResponse(GDPTalentoWA.MiembroPUCPWS.miembroPUCP[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MiembroPUCPWSChannel : GDPTalentoWA.MiembroPUCPWS.MiembroPUCPWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MiembroPUCPWSClient : System.ServiceModel.ClientBase<GDPTalentoWA.MiembroPUCPWS.MiembroPUCPWS>, GDPTalentoWA.MiembroPUCPWS.MiembroPUCPWS {
        
        public MiembroPUCPWSClient() {
        }
        
        public MiembroPUCPWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MiembroPUCPWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MiembroPUCPWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MiembroPUCPWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GDPTalentoWA.MiembroPUCPWS.modificarMiembroPUCPResponse GDPTalentoWA.MiembroPUCPWS.MiembroPUCPWS.modificarMiembroPUCP(GDPTalentoWA.MiembroPUCPWS.modificarMiembroPUCPRequest request) {
            return base.Channel.modificarMiembroPUCP(request);
        }
        
        public int modificarMiembroPUCP(GDPTalentoWA.MiembroPUCPWS.miembroPUCP miembroPUCP) {
            GDPTalentoWA.MiembroPUCPWS.modificarMiembroPUCPRequest inValue = new GDPTalentoWA.MiembroPUCPWS.modificarMiembroPUCPRequest();
            inValue.miembroPUCP = miembroPUCP;
            GDPTalentoWA.MiembroPUCPWS.modificarMiembroPUCPResponse retVal = ((GDPTalentoWA.MiembroPUCPWS.MiembroPUCPWS)(this)).modificarMiembroPUCP(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GDPTalentoWA.MiembroPUCPWS.modificarMiembroPUCPResponse> GDPTalentoWA.MiembroPUCPWS.MiembroPUCPWS.modificarMiembroPUCPAsync(GDPTalentoWA.MiembroPUCPWS.modificarMiembroPUCPRequest request) {
            return base.Channel.modificarMiembroPUCPAsync(request);
        }
        
        public System.Threading.Tasks.Task<GDPTalentoWA.MiembroPUCPWS.modificarMiembroPUCPResponse> modificarMiembroPUCPAsync(GDPTalentoWA.MiembroPUCPWS.miembroPUCP miembroPUCP) {
            GDPTalentoWA.MiembroPUCPWS.modificarMiembroPUCPRequest inValue = new GDPTalentoWA.MiembroPUCPWS.modificarMiembroPUCPRequest();
            inValue.miembroPUCP = miembroPUCP;
            return ((GDPTalentoWA.MiembroPUCPWS.MiembroPUCPWS)(this)).modificarMiembroPUCPAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GDPTalentoWA.MiembroPUCPWS.insertarMiembroPUCPResponse GDPTalentoWA.MiembroPUCPWS.MiembroPUCPWS.insertarMiembroPUCP(GDPTalentoWA.MiembroPUCPWS.insertarMiembroPUCPRequest request) {
            return base.Channel.insertarMiembroPUCP(request);
        }
        
        public int insertarMiembroPUCP(GDPTalentoWA.MiembroPUCPWS.miembroPUCP miembroPUCP) {
            GDPTalentoWA.MiembroPUCPWS.insertarMiembroPUCPRequest inValue = new GDPTalentoWA.MiembroPUCPWS.insertarMiembroPUCPRequest();
            inValue.miembroPUCP = miembroPUCP;
            GDPTalentoWA.MiembroPUCPWS.insertarMiembroPUCPResponse retVal = ((GDPTalentoWA.MiembroPUCPWS.MiembroPUCPWS)(this)).insertarMiembroPUCP(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GDPTalentoWA.MiembroPUCPWS.insertarMiembroPUCPResponse> GDPTalentoWA.MiembroPUCPWS.MiembroPUCPWS.insertarMiembroPUCPAsync(GDPTalentoWA.MiembroPUCPWS.insertarMiembroPUCPRequest request) {
            return base.Channel.insertarMiembroPUCPAsync(request);
        }
        
        public System.Threading.Tasks.Task<GDPTalentoWA.MiembroPUCPWS.insertarMiembroPUCPResponse> insertarMiembroPUCPAsync(GDPTalentoWA.MiembroPUCPWS.miembroPUCP miembroPUCP) {
            GDPTalentoWA.MiembroPUCPWS.insertarMiembroPUCPRequest inValue = new GDPTalentoWA.MiembroPUCPWS.insertarMiembroPUCPRequest();
            inValue.miembroPUCP = miembroPUCP;
            return ((GDPTalentoWA.MiembroPUCPWS.MiembroPUCPWS)(this)).insertarMiembroPUCPAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GDPTalentoWA.MiembroPUCPWS.eliminarMiembroPUCPResponse GDPTalentoWA.MiembroPUCPWS.MiembroPUCPWS.eliminarMiembroPUCP(GDPTalentoWA.MiembroPUCPWS.eliminarMiembroPUCPRequest request) {
            return base.Channel.eliminarMiembroPUCP(request);
        }
        
        public int eliminarMiembroPUCP(int idmiembroPUCP) {
            GDPTalentoWA.MiembroPUCPWS.eliminarMiembroPUCPRequest inValue = new GDPTalentoWA.MiembroPUCPWS.eliminarMiembroPUCPRequest();
            inValue.idmiembroPUCP = idmiembroPUCP;
            GDPTalentoWA.MiembroPUCPWS.eliminarMiembroPUCPResponse retVal = ((GDPTalentoWA.MiembroPUCPWS.MiembroPUCPWS)(this)).eliminarMiembroPUCP(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GDPTalentoWA.MiembroPUCPWS.eliminarMiembroPUCPResponse> GDPTalentoWA.MiembroPUCPWS.MiembroPUCPWS.eliminarMiembroPUCPAsync(GDPTalentoWA.MiembroPUCPWS.eliminarMiembroPUCPRequest request) {
            return base.Channel.eliminarMiembroPUCPAsync(request);
        }
        
        public System.Threading.Tasks.Task<GDPTalentoWA.MiembroPUCPWS.eliminarMiembroPUCPResponse> eliminarMiembroPUCPAsync(int idmiembroPUCP) {
            GDPTalentoWA.MiembroPUCPWS.eliminarMiembroPUCPRequest inValue = new GDPTalentoWA.MiembroPUCPWS.eliminarMiembroPUCPRequest();
            inValue.idmiembroPUCP = idmiembroPUCP;
            return ((GDPTalentoWA.MiembroPUCPWS.MiembroPUCPWS)(this)).eliminarMiembroPUCPAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GDPTalentoWA.MiembroPUCPWS.listarMiembroPUCPResponse GDPTalentoWA.MiembroPUCPWS.MiembroPUCPWS.listarMiembroPUCP(GDPTalentoWA.MiembroPUCPWS.listarMiembroPUCPRequest request) {
            return base.Channel.listarMiembroPUCP(request);
        }
        
        public GDPTalentoWA.MiembroPUCPWS.miembroPUCP[] listarMiembroPUCP() {
            GDPTalentoWA.MiembroPUCPWS.listarMiembroPUCPRequest inValue = new GDPTalentoWA.MiembroPUCPWS.listarMiembroPUCPRequest();
            GDPTalentoWA.MiembroPUCPWS.listarMiembroPUCPResponse retVal = ((GDPTalentoWA.MiembroPUCPWS.MiembroPUCPWS)(this)).listarMiembroPUCP(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GDPTalentoWA.MiembroPUCPWS.listarMiembroPUCPResponse> GDPTalentoWA.MiembroPUCPWS.MiembroPUCPWS.listarMiembroPUCPAsync(GDPTalentoWA.MiembroPUCPWS.listarMiembroPUCPRequest request) {
            return base.Channel.listarMiembroPUCPAsync(request);
        }
        
        public System.Threading.Tasks.Task<GDPTalentoWA.MiembroPUCPWS.listarMiembroPUCPResponse> listarMiembroPUCPAsync() {
            GDPTalentoWA.MiembroPUCPWS.listarMiembroPUCPRequest inValue = new GDPTalentoWA.MiembroPUCPWS.listarMiembroPUCPRequest();
            return ((GDPTalentoWA.MiembroPUCPWS.MiembroPUCPWS)(this)).listarMiembroPUCPAsync(inValue);
        }
    }
}
