DROP PROCEDURE IF EXISTS ELIMINAR_TAREA_ENCARGADO_FOR_UPDATE;

DELIMITER $$

CREATE PROCEDURE ELIMINAR_TAREA_ENCARGADO_FOR_UPDATE(
    IN p_id_tarea INT
)
BEGIN
    DELETE FROM Tarea_Encargado
    WHERE id_tarea = p_id_tarea;
END$$

DELIMITER ;